import { AuthProvider } from '@/app/context';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Navbar, ThemeProvider } from './components';
import './globals.css';
import { env } from './lib';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  /**
   * Replace `https://acme.com` with URL of the hosted version aka `https://weichain-nextjs-template.org`
   * Work in pair with `alternates`
   */
  metadataBase: new URL(env.APP_BASE_URL),
  title: {
    template: '%s | NextJS Template',
    default: 'NextJS Template',
  },
  description: 'Generated by create nextjs template',
  applicationName: 'NextJS Template',
  keywords: ['Next.js', 'React', 'JavaScript', 'NextJS Template'],
  authors: [{ name: 'John' }, { name: 'Doe', url: 'https://nextjs.org' }],
  creator: 'Bob',
  publisher: 'Alice',
  alternates: {
    canonical: '/',
    languages: {
      'en-US': '/en-US',
    },
  },
  openGraph: {
    title: 'NextJS Template',
    description: 'Generated by create nextjs template',
    url: env.APP_BASE_URL,
    siteName: 'weichain next generator',
    type: 'website',
    locale: 'en_US',
  },
  twitter: {
    title: 'NextJS Template',
    description: 'Generated by create nextjs template',
    site: 'weichain next generator',
    card: 'summary_large_image',
    siteId: '@nextjs-template',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={inter.className}>
        <AuthProvider>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            <main className='flex justify-center items-start p-6 min-h-screen'>
              {children}
            </main>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
